require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SleepsController do

  # This should return the minimal set of attributes required to create a valid
  # Sleep. As you add validations to Sleep, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "index" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SleepsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all sleeps as @sleeps" do
      sleep = Sleep.create! valid_attributes
      get :index, {}, valid_session
      assigns(:sleeps).should eq([sleep])
    end
  end

  describe "GET show" do
    it "assigns the requested sleep as @sleep" do
      sleep = Sleep.create! valid_attributes
      get :show, {:id => sleep.to_param}, valid_session
      assigns(:sleep).should eq(sleep)
    end
  end

  describe "GET new" do
    it "assigns a new sleep as @sleep" do
      get :new, {}, valid_session
      assigns(:sleep).should be_a_new(Sleep)
    end
  end

  describe "GET edit" do
    it "assigns the requested sleep as @sleep" do
      sleep = Sleep.create! valid_attributes
      get :edit, {:id => sleep.to_param}, valid_session
      assigns(:sleep).should eq(sleep)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Sleep" do
        expect {
          post :create, {:sleep => valid_attributes}, valid_session
        }.to change(Sleep, :count).by(1)
      end

      it "assigns a newly created sleep as @sleep" do
        post :create, {:sleep => valid_attributes}, valid_session
        assigns(:sleep).should be_a(Sleep)
        assigns(:sleep).should be_persisted
      end

      it "redirects to the created sleep" do
        post :create, {:sleep => valid_attributes}, valid_session
        response.should redirect_to(Sleep.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sleep as @sleep" do
        # Trigger the behavior that occurs when invalid params are submitted
        Sleep.any_instance.stub(:save).and_return(false)
        post :create, {:sleep => { "index" => "invalid value" }}, valid_session
        assigns(:sleep).should be_a_new(Sleep)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Sleep.any_instance.stub(:save).and_return(false)
        post :create, {:sleep => { "index" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sleep" do
        sleep = Sleep.create! valid_attributes
        # Assuming there are no other sleeps in the database, this
        # specifies that the Sleep created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Sleep.any_instance.should_receive(:update).with({ "index" => "1" })
        put :update, {:id => sleep.to_param, :sleep => { "index" => "1" }}, valid_session
      end

      it "assigns the requested sleep as @sleep" do
        sleep = Sleep.create! valid_attributes
        put :update, {:id => sleep.to_param, :sleep => valid_attributes}, valid_session
        assigns(:sleep).should eq(sleep)
      end

      it "redirects to the sleep" do
        sleep = Sleep.create! valid_attributes
        put :update, {:id => sleep.to_param, :sleep => valid_attributes}, valid_session
        response.should redirect_to(sleep)
      end
    end

    describe "with invalid params" do
      it "assigns the sleep as @sleep" do
        sleep = Sleep.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Sleep.any_instance.stub(:save).and_return(false)
        put :update, {:id => sleep.to_param, :sleep => { "index" => "invalid value" }}, valid_session
        assigns(:sleep).should eq(sleep)
      end

      it "re-renders the 'edit' template" do
        sleep = Sleep.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Sleep.any_instance.stub(:save).and_return(false)
        put :update, {:id => sleep.to_param, :sleep => { "index" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sleep" do
      sleep = Sleep.create! valid_attributes
      expect {
        delete :destroy, {:id => sleep.to_param}, valid_session
      }.to change(Sleep, :count).by(-1)
    end

    it "redirects to the sleeps list" do
      sleep = Sleep.create! valid_attributes
      delete :destroy, {:id => sleep.to_param}, valid_session
      response.should redirect_to(sleeps_url)
    end
  end

end
