require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe StressesController do

  # This should return the minimal set of attributes required to create a valid
  # Stress. As you add validations to Stress, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "integer" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StressesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all stresses as @stresses" do
      stress = Stress.create! valid_attributes
      get :index, {}, valid_session
      assigns(:stresses).should eq([stress])
    end
  end

  describe "GET show" do
    it "assigns the requested stress as @stress" do
      stress = Stress.create! valid_attributes
      get :show, {:id => stress.to_param}, valid_session
      assigns(:stress).should eq(stress)
    end
  end

  describe "GET new" do
    it "assigns a new stress as @stress" do
      get :new, {}, valid_session
      assigns(:stress).should be_a_new(Stress)
    end
  end

  describe "GET edit" do
    it "assigns the requested stress as @stress" do
      stress = Stress.create! valid_attributes
      get :edit, {:id => stress.to_param}, valid_session
      assigns(:stress).should eq(stress)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Stress" do
        expect {
          post :create, {:stress => valid_attributes}, valid_session
        }.to change(Stress, :count).by(1)
      end

      it "assigns a newly created stress as @stress" do
        post :create, {:stress => valid_attributes}, valid_session
        assigns(:stress).should be_a(Stress)
        assigns(:stress).should be_persisted
      end

      it "redirects to the created stress" do
        post :create, {:stress => valid_attributes}, valid_session
        response.should redirect_to(Stress.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved stress as @stress" do
        # Trigger the behavior that occurs when invalid params are submitted
        Stress.any_instance.stub(:save).and_return(false)
        post :create, {:stress => { "integer" => "invalid value" }}, valid_session
        assigns(:stress).should be_a_new(Stress)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Stress.any_instance.stub(:save).and_return(false)
        post :create, {:stress => { "integer" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested stress" do
        stress = Stress.create! valid_attributes
        # Assuming there are no other stresses in the database, this
        # specifies that the Stress created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Stress.any_instance.should_receive(:update).with({ "integer" => "MyString" })
        put :update, {:id => stress.to_param, :stress => { "integer" => "MyString" }}, valid_session
      end

      it "assigns the requested stress as @stress" do
        stress = Stress.create! valid_attributes
        put :update, {:id => stress.to_param, :stress => valid_attributes}, valid_session
        assigns(:stress).should eq(stress)
      end

      it "redirects to the stress" do
        stress = Stress.create! valid_attributes
        put :update, {:id => stress.to_param, :stress => valid_attributes}, valid_session
        response.should redirect_to(stress)
      end
    end

    describe "with invalid params" do
      it "assigns the stress as @stress" do
        stress = Stress.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Stress.any_instance.stub(:save).and_return(false)
        put :update, {:id => stress.to_param, :stress => { "integer" => "invalid value" }}, valid_session
        assigns(:stress).should eq(stress)
      end

      it "re-renders the 'edit' template" do
        stress = Stress.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Stress.any_instance.stub(:save).and_return(false)
        put :update, {:id => stress.to_param, :stress => { "integer" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested stress" do
      stress = Stress.create! valid_attributes
      expect {
        delete :destroy, {:id => stress.to_param}, valid_session
      }.to change(Stress, :count).by(-1)
    end

    it "redirects to the stresses list" do
      stress = Stress.create! valid_attributes
      delete :destroy, {:id => stress.to_param}, valid_session
      response.should redirect_to(stresses_url)
    end
  end

end
